project/pages/urls.py
from django.urls import path , include
from django.conf.urls import url

from . import views

urlpatterns = [
    path('', views.index_view , name='index'),
    path('about/', views.about_view , name='about'),
    path('store/', views.store_view , name='store'),
    path('search/', views.search_view , name='search'),
    path('logout/', views.logout_view , name='logout'),
    path('<int:id>',views.delete_one_purchase , name='del'),
    path('del-cart/',views.delete_cart, name='del-cart'),
    path('dashboard/', views.profile_view , name='profile'),
    path('news/', views.news_view , name='news'),
    path('<int:id>', views.news_detail_view, name='newsdetail'),
    path('purchase-success/', views.finished_purchase , name='sold'),
    #url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        #views.activate, name='activate'),
]

project/project/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('pages.urls')),
]

project/cap/models.py
from django.db import models
from pages.choices import CAP_CHOICES
# Create your models here.

class Cap(models.Model):
    NAME_CHOICES = [
        ('cap', 'کپ'),
    ]

    name = models.CharField(max_length=100 , choices=NAME_CHOICES , default='cap')
    
    MODEL_CHOICES = [
        ('deep', 'گود'),
        ('flat', 'تخت'),
    ]
    مدل = models.CharField(max_length=100 , choices= MODEL_CHOICES)
    سایز = models.CharField(max_length=100 , choices= CAP_CHOICES)
    قیمت = models.IntegerField()
    NUMBER_CHOICES = [
        (3000, 3000),
        (2000, 2000),
        (1000, 1000),
        (500, 500),
        (300, 300),
        (250, 250),
        (200, 200),
        (100, 100),
        (75, 75),
        (50, 50),
    ]
    تعداد_کیسه = models.IntegerField(null=True , choices=NUMBER_CHOICES)

    def __str__(self):
        return self.name

project/news/models.py
from django.db import models
from datetime import datetime
# Create your models here.

class News(models.Model):
    عنوان = models.CharField(max_length=255)
    توضیحات = models.TextField()
    image = models.ImageField(upload_to='photos', blank=True)
    تاریخ_انتشار = models.DateTimeField (default=datetime.now)

    def __str__(self):
        return self.عنوان

project/news/views.py
from django.shortcuts import render

# Create your views here.

project/templates/pages/dashboard.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
{% endblock %}

{% block main %}
<main dir="rtl" class="bg-color-daisy">
    <div class="row profileShadow " dir="rtl">
        <div class="container mx-auto justify-content-center d-flex">
            <div class="text-right mr-2 " dir="rtl">
                <img class="picture" src="{% static 'images/user.jpg' %}" width="150">

            </div>
            <div class="ml-auto pr-2">
                <p class=" pt-4">{{ user.first_name }} {{ user.last_name }}</p>
            </div>
            <div class="pt-4  ml-2">
                <a class="setting p-1 mr-3 btn" href="#">
                    <i class="fas fa-cog"></i>
                    تنظیمات
                </a>

            </div>
        </div>

    </div>



    <section id="profile_content" class="row">
        <div class="container py-5 mx-auto">

            <article id="content-head" class="row text-center py-4 m-0">

                <div class="item  col-4 mr-4 btn btn-info-my" data-toggle="collapse" data-target="#addition">
                       سوابق خرید
                </div>
                <div class="item  col-4 ml-4 mr-auto btn btn-info-my" data-toggle="collapse" data-target="#specifications">
                     سبد خرید
                </div>

            </article>


            <article class="content-body ">

                <article id="addition" class="collapse show" data-parent="#profile_content">
                    <div class="card border-0">

                        <div class="card-header bg-color-gray" style="border-radius: 0;">
                            <div class=" text-center">
                                <div class="  w-100" style="font-size: x-large;">
                                    سوابق خرید
                                </div>

                            </div>
                        </div>

                        <div class="card-body py-5 bg-color-daisy table-responsive">

                            <table class="table table-striped " >
                                <thead class="text-center" >
                                    <tr style="border-bottom: 2px black solid">
                                        <th>ردیف</th>
                                        <th>نام محصول</th>
                                        <th>نوع محصول</th>
                                        <th>نوع درز</th>
                                        <th>سایز</th>
                                        <th>قیمت</th>
                                        <th>تعداد</th>
                                        <th>تاریخ خرید</th>
                                    </tr>
                                </thead>

                                <tbody class="text-center">
                                <!--حلقه ی for برای نمایش سوابق خرید-->
                                    <!--حلقه ی for برای نمایش سوابق خرید-->
                                    <!--حلقه ی for برای نمایش سوابق خرید-->

                                    <tr style="border-bottom: 2px black solid">
                                        <td>1</td>
                                        <td>محصول 1</td>
                                        <td>نوع 1</td>
                                        <td>درز 3</td>
                                        <td>85</td>
                                        <td>984000</td>
                                        <td>230</td>
                                        <td>98/6/5</td>
                                    </tr>

                                    <!--حلقه ی for برای نمایش سوابق خرید-->
                                    <!--حلقه ی for برای نمایش سوابق خرید-->
                                    <!--حلقه ی for برای نمایش سوابق خرید-->

                                </tbody>

                            </table>

                        </div>

                    </div>
                </article>

                <article id="specifications" class="collapse" data-parent="#profile_content">
                    <div class="card border-0">

                        
                        <div class="card-header bg-color-gray" style="border-radius: 0;">
                                <div class=" text-center">
                                    <div class="  w-100" style="font-size: x-large;">
                                            سبد خرید
                                    </div>
    
                                </div>
                            </div>

                        <div class="card-body py-5 bg-color-daisy">

                            <table class="table table-striped " >
                                <thead class="text-center" >
                                <tr style="border-bottom: 2px black solid">
                                    <th>نام محصول</th>
                                    <th>نوع محصول</th>
                                    <th>سایز</th>
                                    <th>قیمت</th>
                                    <th>تعداد</th>
                                </tr>
                                </thead>
                                {% if purchased %}
                                {% for item in purchased %}
                                <tbody class="text-center">
                                <tr style="border-bottom: 2px black solid">
                                    <td>{{ item.name }}</td>
                                    <td>{{ item.model }}</td>
                                    <td>{{ item.size }}</td>
                                    <td>{{ item.price }}</td>
                                    <td>{{ item.number }}</td>
                                    
                                </tr>
                                {% endfor %}
                                {% else %}
                                <p>سبد خرید شما خالی است</p>
                                {% endif %}
                            </table>

                        </div>

                    </div>
                </article>

            </article>
        </div>
        
    </section>
    <!-- <div  class="col-md-3 mt-1 mb-5 my-md-5 col-8 mx-auto">
            <div style="background-color: bisque;" class="item text-center" data-toggle="collapse" data-target="#addition">

                    <i class="fas fa-shopping-cart" ></i>
                    سبد خرید شما
                </div>
               
            </div>
            {% if purchased %}
            {% for item in purchased %}
            <div class="cartBody">
                <div class="cart-item">
                    <p class="text-center mt-1">
                       {{item.name}}  {{ item.model }}
                    </p>
                    <div class="d-flex">
                        <p class="mr-2">
                            {{ item.price }} تومان هزار
                        </p>
                        <div class="d-flex mr-auto pl-4 pt-1">
                            <i class="fa fa-plus"></i>
                            <i class="mx-2">{{ item.number }}</i>
                            <i class="fa fa-minus"></i>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="d-flex mt-5">
                <p class="mr-1">
                    جمع خرید
                </p>
                <p class="mr-auto ml-1">
                   {{ summ }},000 تومان
                </p>
            </div>
            {% else %}
            <p> سبد خرید شما خالی است </p>
            {% endif %}
            <div>
                <a class="btn btn-outline-info w-100" href="#">
                    تایید و پرداخت
                </a>
            </div>
        </div> -->

</main>
{% endblock %}

project/templates/pages/search.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
<div class="text-right" dir="rtl">
        <div class="container-fluid pt-2">
    
    
    
            <section id="grouping" class="row">
                <div class=" col-md-9 " >
                    <div class="card container mx-auto p-0" style="border: 1px #cda34f solid">
                        <div class="card-header  info-color white-text text-center">
                            فیلتر محصولات
                        </div>
                        <div id="cardbody" class="card-body text-right" >
    
    
                            <form class="row mx-auto" action="{% url 'search' %}">
                                <div class="col-10 col-md-6 col-sm-8 mx-auto">
                                    <div class="md-form mt-2 mx-auto"  >
                                        <label>نام محصول:</label>
                                        <input placeholder="عبارت مورد نظر را جستجو کنید ..." class="form-control underline shadow SetWidth"  >
                                    </div>
                                </div>
    
                                <div class="col-10 col-md-6 col-sm-8 mx-auto ">
                                    <div  class="md-form mt-2 mx-auto " >
                                        <label>انتخاب محصول:</label>
                                        <select name="name" class="custom-select form-control SetWidth">
                                                <option selected="true" disabled="disabled">نام محصول</option>
                                            <option value="elbow">زانویی</option>
                                            <option value="tee">سه راهی</option>
                                            <option value="nippel"> سر دنده</option>
                                            <option value="cap">کپ</option>
                                            <option value="reducer">تبدیل</option>
                                        </select>
                                    </div>
                                </div>
    
                                <div class="col-10 col-md-6 col-sm-8 mx-auto">
                                    <div  class="md-form mt-2 mx-auto " >
                                        <label>نوع محصول:</label>
                                        <select  name="مدل" class="custom-select form-control SetWidth">
                                            <option selected="true" disabled="disabled">نوع محصول</option>
                                            <option value="darzdar">درزدار</option>
                                            <option value="standard">استاندارد</option>
                                            <option value="mannesman">مانیسمان</option>
                                            <option value="type40">رده چهل</option>
                                            <option value="flat">تخت</option>
                                            <option value="deep">گود</option>
                                        </select>
                                    </div>
                                </div>
    
                                <div class="col-10 col-md-6 col-sm-8 mx-auto">
                                    <div class="md-form mx-auto" style="margin-top: 40px;">
                                        <button class="btn btn-outline-info btn-block SetWidth" type="submit">اعمال فیلتر</button>
                                    </div>
                                </div>
                                <!-- <button class="btn btn-outline-info btn-block mt-4" type="submit">اعمال فیلتر</button> -->
                            </form>
    
    
    
    
    
                        </div>
    
                    </div>
                    <div id="productList" class="row pt-2 px-0 ">
    
                        <!--حلقه ی for برای محصولات فروشگاه-->
                        <!--حلقه ی for برای محصولات فروشگاه-->
                        <!--حلقه ی for برای محصولات فروشگاه-->
                    {% if products %}
                        {% for product in products %}
                        <div class="col-11 col-md-6 mx-auto">
                            
                            <div class="card mb-3 mx-auto" style="max-width: 540px;border: 1px #4fbacd solid">
                                <div class="row no-gutters" >
                                    <div class="col-4">
                                        <img src="{% static 'images/elbow.jpg' %}" class="card-img" alt="...">
                                    </div>
                                    <div class="col-8">
                                         {% if user.is_authenticated %}
                                            <form  class="row mx-auto" action="{% url 'search' %}" method="POST"> {% csrf_token %}
                                                    <input style="display:none" type="text" name="name" value="{{ product.get_name_display }}">
                                                    <input style="display:none" type="text" name="model" value="{{ product.get_مدل_display }}">
                                                    <input style="display:none" type="text" name="size" value="{{ product.get_سایز_display }}">
                                                    <input style="display:none" type="text" name="number" value="{{ product.get_تعداد_کیسه_display }}">
                                                    <input style="display:none" type="text" name="price" value="{{ product.قیمت }}">
                                                    {% else %}
                                                    <p>برای خرید این محصول لطفا ابتدا ثبت نام کنید</p>
                                                    {% endif %}
                                        <div class="card-body">
                                            <div value="name" class="card-title color-white radius p-1 d-inline" style="background-color: #005c78;">
                                                    {{ product.get_name_display }}
                                                <strong class="" >{{ product.get_مدل_display }}</strong>
                                            </div>
                                            <p class="card-text mt-2" style="font-size: small" > تعداد در کیسه: {{ product.get_تعداد_کیسه_display }}</p>
                                            <hr>
                                            <p class="card-text" style="font-size: small" > سایز : {{ product.get_سایز_display }}</p>
                                            <hr>
                                            <p class="card-text" style="font-size: small" > قیمت: {{ product.قیمت }} هزار تومان </p>
                                            <button class="btn bg-color-gold" type="submit" style="font-size: small">اضافه به سبد خرید</button>
                                            </form>
                                            
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    {% endif %}    
                        
                        <!--حلقه ی for برای محصولات فروشگاه-->
                        <!--حلقه ی for برای محصولات فروشگاه-->
                        <!--حلقه ی for برای محصولات فروشگاه-->
    
                    </div>
    
                    <div class="content-pagination">
                        <a href="#">۱</a>
                        <a href="#">۲</a>
                        <a href="#">۳</a>
                        <span >…</span>
                        <a href="#">۱۴</a>
                        <a href="#">بعدی »</a>
                    </div>
                </div>
    
                <div  class="col-md-3 mt-1 mb-5 my-md-5 col-8 mx-auto">
                    <div class="cartHeader p-3 radius">
                        <i class="fas fa-shopping-cart" ></i>
                        سبد خرید شما
                    </div>
                    {% if purchased %}
                    {% for item in purchased %}
                    
                    <div class="cartBody">
                        <div class="cart-item">
                            <div class="d-flex">
                                    <p class="mr-2 mt-1 text-center bg-color-mine text-white p-1 radius setWidth" >
                                            {{item.name}}  {{ item.model }}
                                    </p>
                                    <p class="ml-2 mr-auto text-center mt-1 bg-color-mine text-white p-1 radius setWidth" >
                                        سایز: {{ item.size }}
                                    </p>
                            </div>
                            
                            <div class="d-flex">
                                <p class="mr-2  mt-1 bg-color-mine text-center text-white p-1 radius setWidth" >
                                    {{ item.price }} هزار تومان
                                </p>
                                <p class="ml-2 mr-auto text-center mt-1 bg-color-mine text-white p-1 radius setWidth" >
                                    
                                    {{ item.number }}
                                    
                                </p>
                            </div>
			<div class="d-flex">
			 <a class="btn btn-outline -danger text-center mt-1 text-red p-1 radius setWidth" href="{% url 'del' item.id %}">
				حذف محصول
			</a>
			</div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="d-flex mt-5">
                        <p class="mr-1">
                            جمع خرید
                        </p>
                        <p class="mr-auto ml-1">
                           {{ summ }},000 تومان
                        </p>
                    </div>
                    {% else %}
                    <p> سبد خرید شما خالی است </p>
                    {% endif %}
                    <div>
                        <a class="btn btn-outline-info w-100" href="{% url 'sold' %}">
                            تایید و پرداخت
                        </a>
                    </div>
                </div>
            </section>
    
    
    
    
        </div>
{% endblock %}

project/templates/pages/store.html
{% extends 'base.html' %}
{% load static %}
{% block main %}
<div class="text-right" dir="rtl">
        <div class="container-fluid pt-2">
    
    
    
            <section id="grouping" class="row">
                <div class=" col-md-9 " >
                    <div class="card container mx-auto p-0" style="border: 1px #cda34f solid">
                        <div class="card-header  info-color white-text text-center">
                            فیلتر محصولات
                        </div>
                        <div id="cardbody" class="card-body text-right" >
    
    
                            <form class="row mx-auto" action="{% url 'search' %}">
                                <div class="col-10 col-md-6 col-sm-8 mx-auto">
                                    <div class="md-form mt-2 mx-auto"  >
                                        <label>نام محصول:</label>
                                        <input placeholder="عبارت مورد نظر را جستجو کنید ..." class="form-control underline shadow SetWidth"  >
                                    </div>
                                </div>
    
                                <div class="col-10 col-md-6 col-sm-8 mx-auto ">
                                    <div  class="md-form mt-2 mx-auto " >
                                        <label>انتخاب محصول:</label>
                                        <select name="name" class="custom-select form-control SetWidth">
                                                <option selected="true" disabled="disabled">نام محصول</option>
                                            <option value="elbow">زانویی</option>
                                            <option value="tee">سه راهی</option>
                                            <option value="nippel"> سر دنده</option>
                                            <option value="cap">کپ</option>
                                            <option value="reducer">تبدیل</option>
                                        </select>
                                    </div>
                                </div>
    
                                <div class="col-10 col-md-6 col-sm-8 mx-auto">
                                    <div  class="md-form mt-2 mx-auto " >
                                        <label>نوع محصول:</label>
                                        <select  name="مدل" class="custom-select form-control SetWidth">
                                            <option selected="true" disabled="disabled">نوع محصول</option>
                                            <option value="darzdar">درزدار</option>
                                            <option value="standard">استاندارد</option>
                                            <option value="mannesman">مانیسمان</option>
                                            <option value="type40">رده چهل</option>
                                            <option value="flat">تخت</option>
                                            <option value="deep">گود</option>
                                        </select>
                                    </div>
                                </div>
    
                                <div class="col-10 col-md-6 col-sm-8 mx-auto">
                                    <div class="md-form mt-2 mx-auto">
                                        <label>اندازه:</label>
                                        <div class="">
                                            <input type="checkbox"  class="custom-checkbox">
                                            <label class="m-0">همه اندازه ها</label>
                                        </div>
                                        <div class="">
                                            <input type="checkbox"  class="checkbox-custom">
                                            <label class="m-0">کوچکتر از 5</label>
                                        </div>
                                        <div class="">
                                            <input type="checkbox"  class="custom-checkbox">
                                            <label class="m-0">کوچکتر از 10</label>
                                        </div>
                                        <div class="">
                                            <input type="checkbox"  class="custom-checkbox">
                                            <label class="m-0">کوچکتر از 20</label>
                                        </div>
                                        <div class="">
                                            <input type="checkbox"  class="custom-checkbox">
                                            <label class="m-0">کوچکتر از 30</label>
                                        </div>
                                    </div>
                                </div>
                                <button class="btn btn-success btn-block mt-4" type="submit">اعمال فیلتر</button>
                            </form>
    
    
    
    
    
                        </div>
    
                    </div>
                    <div id="productList" class="row pt-2 px-0 ">
    
                        <!--حلقه ی for برای محصولات فروشگاه-->
                        <!--حلقه ی for برای محصولات فروشگاه-->
                        <!--حلقه ی for برای محصولات فروشگاه-->
                    {% if items %}
                        {% for product in items %}
                        <div class="col-11 col-md-6 mx-auto">
                            
                            <div class="card mb-3 mx-auto" style="max-width: 540px;border: 1px #cda34f solid">
                                <div class="row no-gutters" >
                                    <div class="col-4">
                                        <img src="{% static 'images/elbow.jpg' %}" class="card-img" alt="...">
                                    </div>
                                    <div class="col-8">
                                         {% if user.is_authenticated %}
                                            <form  class="row mx-auto" action="{% url 'search' %}" method="POST"> {% csrf_token %}
                                                    <input style="display:none" type="" name="name" value="{{ product.get_name_display }}">
                                                    <input style="display:none" type="text" name="model" value="{{ product.get_مدل_display }}">
                                                    <input style="display:none" type="text" name="number" value="{{ product.get_تعداد_کیسه_display }}">
                                                    <input style="display:none" type="text" name="price" value="{{ product.قیمت }}">
                                                    {% endif %}
                                        <div class="card-body">
                                            <h5 value="name" class="card-title">
                                                    {{ product.get_name_display }}
                                                <strong class="bg-color-greenery color-white radius p-1" >{{ product.get_مدل_display }}</strong>
                                            </h5>
                                            <p class="card-text" style="font-size: small" > تعداد در کیسه: {{ product.get_تعداد_کیسه_display }}</p>
                                            <p class="card-text" style="font-size: small" > سایز : {{ product.get_سایز_display }}</p>
                                            <p class="card-text" style="font-size: small" > قیمت: {{ product.قیمت }} هزار تومان </p>
                                            <button class="btn bg-color-gold" type="submit" style="font-size: small">اضافه به سبد خرید</button>
                                            </form>
                                            
                                            <p class="card-text"><small class="text-muted">آخرین به روزرسانی 3 دقیقه پیش</small></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                    {% endif %}    
    
                        <!--حلقه ی for برای محصولات فروشگاه-->
                        <!--حلقه ی for برای محصولات فروشگاه-->
                        <!--حلقه ی for برای محصولات فروشگاه-->
    
                    </div>
    
                    <div class="content-pagination">
                        <a href="#">۱</a>
                        <a href="#">۲</a>
                        <a href="#">۳</a>
                        <span >…</span>
                        <a href="#">۱۴</a>
                        <a href="#">بعدی »</a>
                    </div>
                </div>
    
                <div  class="col-md-3 mt-1 mb-5 my-md-5 col-8 mx-auto">
                    <div class="cartHeader p-3 radius">
                        <i class="fas fa-shopping-cart" ></i>
                        سبد خرید شما
                    </div>
                    {% if purchased %}
                    {% for item in purchased %}
                    <div class="cartBody">
                        <div class="cart-item">
                            <p class="text-center mt-1">
                               {{item.name}}  {{ item.model }}
                            </p>
                            <div class="d-flex">
                                <p class="mr-2">
                                    {{ item.price }} تومان هزار
                                </p>
                                <div class="d-flex mr-auto pl-4 pt-1">
                                    <i class="fa fa-plus"></i>
                                    <i class="mx-2">{{ item.number }}</i>
                                    <i class="fa fa-minus"></i>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                    <div class="d-flex mt-5">
                        <p class="mr-1">
                            جمع خرید
                        </p>
                        <p class="mr-auto ml-1">
                           {{ summ }},000 تومان
                        </p>
                    </div>
                    {% else %}
                    <p> سبد خرید شما خالی است </p>
                    {% endif %}
                    <div>
                        <a class="btn btn-outline-info w-100" href="#">
                            تایید و پرداخت
                        </a>
                    </div>
                </div>
            </section>
    
    
    
    
        </div>
{% endblock %}